name: jellyfin-tv build

on:
  workflow_dispatch:
  
# permissions:
#   contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: jellyfin/jellyfin-androidtv
          ref: master

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set JELLYFIN_VERSION
        # run: echo "JELLYFIN_VERSION=$(echo ${GITHUB_REF#refs/tags/v} | tr / -)" >> $GITHUB_ENV
        run: |
            echo "JELLYFIN_VERSION=0.19.0" >> $GITHUB_ENV 
        

      - name: Assemble release files
        run: ./gradlew assemble bundleRelease versionTxt

      - name: Sign APK
        id: signApk
        uses: r0adkll/sign-android-release@v1 # tag=v1
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}


      - name: Prepare release archive
        run: |
          mkdir -p build/jellyfin-publish
          mv app/build/outputs/apk/*/jellyfin-androidtv-*-debug.apk build/jellyfin-publish/
          mv ${{ steps.signApk.outputs.signedReleaseFile }} build/jellyfin-publish/jellyfin-androidtv-v${{ env.JELLYFIN_VERSION }}-release.apk
          mv app/build/version.txt build/jellyfin-publish/
      

      - name: Create a release
        uses: "ncipollo/release-action@v1"
        with:
          makeLatest: true
          allowUpdates: true
          tag: "jellyfin-tv"
          artifacts: build/jellyfin-publish/*



          
